blank_issues_enabled: false
contact_links:
  - name: Stell eine Frage
    url: https://github.com/pragmaticag/mailer/discussions/new?category=q-a
    about: Bitte die Community um Hilfe
  - name: Schlag neue Funktionalität vor
    url: https://github.com/pragmaticag/mailer/discussions/new?category=ideas
    about: Teile deine Ideen für neue Funktionen
  - name: Einen Fehler melden
    url: https://github.com/pragmaticag/mailer/issues/new
    about: Melde einen reproduzierbaren Fehler
